version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: "wednesday"
    open-pull-requests-limit: 10
    ignore:
      # Ignore patch updates for all dependencies
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    groups:
      npm-dependencies:
        patterns:
          - "*"
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
    groups:
      github-actions:
        patterns:
          - "*"
  # Docker (devcontainer)
  - package-ecosystem: "docker"
    directory: "/.devcontainer"
    schedule:
      interval: "weekly"
      day: "wednesday"